"""added sentiment column

Revision ID: 2c7915255466
Revises: 
Create Date: 2019-07-16 12:14:55.838697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7915255466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_url', sa.String(), nullable=False),
    sa.Column('mobile_name', sa.String(), nullable=False),
    sa.Column('mobile_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('review', sa.Column('count_words', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('sentiment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'sentiment')
    op.drop_column('review', 'count_words')
    op.drop_table('mobiles')
    # ### end Alembic commands ###
